version: '3'
services:
  app:
    build: .
    volumes:
      - ./back/data/:/usr/src/app/data
    image: app:latest
    container_name: app
    ports:
      - 7070:7070
    networks:
      - app_network

networks:
  app_network:
